# Generated by Django 4.2.11 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaile',
            name='trailer_link',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
