# Generated by Django 4.2.11 on 2024-03-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detaile_app', '0002_alter_detaile_trailer_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaile',
            old_name='image',
            new_name='img',
        ),
    ]
