# Generated by Django 4.2.11 on 2024-03-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detaile_app', '0003_rename_image_detaile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detaile',
        ),
    ]
