# Generated by Django 4.2.11 on 2024-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0002_moviedetailes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetailes',
            name='trailer_link',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
