# Generated by Django 4.2.11 on 2024-03-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0003_alter_moviedetailes_trailer_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieDetailes',
            new_name='DetailesMovie',
        ),
    ]
