# Generated by Django 4.2.11 on 2024-03-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0004_rename_moviedetailes_detailesmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailesMovie',
            new_name='Detailes',
        ),
    ]
