# Generated by Django 4.2.11 on 2024-03-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0005_rename_detailesmovie_detailes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detailes',
        ),
    ]
